### ISSUE TITLE
Labels on X & Y-axis can disappear when resizing snapshot

### ISSUE THREAD

**Issue by evahri** [qlik-oss/sn-scatter-plot#179] opened 2022-01-19 20:28 UTC
Same behavior in snapshots taken with compressed data and normal data.

1. Create a scatterplot, preferably zoom in a bit and note the labels of the intervals on X & Y-axis.
2. Take a snapshot
3. Under Storytelling mode, pull in the snapshot and resize it to smaller and bigger. Note that the labels can disappear and appear again. In old scatter plot the labels don't disappear when resizing snapshot.

![scatterplot_snapshot_resize](https://user-images.githubusercontent.com/92570566/150208550-2fe078e5-0ea4-41f1-ba60-39f10e24e780.gif)

**Comment by quanho** [comment] 2022-02-02 08:03
The same root cause as #191.

**Comment by bao-ho** [comment] 2022-02-06 19:19
FIxed by fixing #191

**Comment by bao-ho** [comment] 2022-02-06 19:20
FIxed by fixing #191

**Closed by bao-ho** 2022-02-06 19:20 UTC
